//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portfolio.Common.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found.
        /// </summary>
        public static string Error_Category_Not_Found {
            get {
                return ResourceManager.GetString("Error_Category_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an error occured.
        /// </summary>
        public static string Error_General {
            get {
                return ResourceManager.GetString("Error_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inactive refresh token.
        /// </summary>
        public static string Error_InactiveRefreshToken {
            get {
                return ResourceManager.GetString("Error_InactiveRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid refresh token.
        /// </summary>
        public static string Error_InvalidRefreshToken {
            get {
                return ResourceManager.GetString("Error_InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Email or Password.
        /// </summary>
        public static string Error_Login {
            get {
                return ResourceManager.GetString("Error_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item not found.
        /// </summary>
        public static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported Extantion.
        /// </summary>
        public static string Error_NotSupportedExtantion {
            get {
                return ResourceManager.GetString("Error_NotSupportedExtantion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is expired.
        /// </summary>
        public static string Error_OTPExpired {
            get {
                return ResourceManager.GetString("Error_OTPExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is Wrong.
        /// </summary>
        public static string Error_OTPWrong {
            get {
                return ResourceManager.GetString("Error_OTPWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        public static string Error_Product_Not_Found {
            get {
                return ResourceManager.GetString("Error_Product_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rate must be between 0 and 5.
        /// </summary>
        public static string Error_RateLimit {
            get {
                return ResourceManager.GetString("Error_RateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field is required.
        /// </summary>
        public static string Error_RequiredField {
            get {
                return ResourceManager.GetString("Error_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in translatable content.
        /// </summary>
        public static string Error_TranslatableContent {
            get {
                return ResourceManager.GetString("Error_TranslatableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email already in use.
        /// </summary>
        public static string Error_UserEmailExist {
            get {
                return ResourceManager.GetString("Error_UserEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email is not exist.
        /// </summary>
        public static string Error_UserEmailNotExist {
            get {
                return ResourceManager.GetString("Error_UserEmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userName already in use.
        /// </summary>
        public static string Error_UserNameExist {
            get {
                return ResourceManager.GetString("Error_UserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number already in use.
        /// </summary>
        public static string Error_UserPhoneExist {
            get {
                return ResourceManager.GetString("Error_UserPhoneExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity system error.
        /// </summary>
        public static string IdentityError_DefaultIdentityError {
            get {
                return ResourceManager.GetString("IdentityError_DefaultIdentityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; already exists.
        /// </summary>
        public static string IdentityError_DuplicateEmail {
            get {
                return ResourceManager.GetString("IdentityError_DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; already exists.
        /// </summary>
        public static string IdentityError_DuplicateRoleName {
            get {
                return ResourceManager.GetString("IdentityError_DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name &apos;{0}&apos; already exists.
        /// </summary>
        public static string IdentityError_DuplicateUserName {
            get {
                return ResourceManager.GetString("IdentityError_DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0} is invalid.
        /// </summary>
        public static string IdentityError_InvalidEmail {
            get {
                return ResourceManager.GetString("IdentityError_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is invalid.
        /// </summary>
        public static string IdentityError_InvalidRoleName {
            get {
                return ResourceManager.GetString("IdentityError_InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name &apos;{0}&apos; is invalid.
        /// </summary>
        public static string IdentityError_InvalidUserName {
            get {
                return ResourceManager.GetString("IdentityError_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided password dosen&apos;t match your saved password.
        /// </summary>
        public static string IdentityError_PasswordMismatch {
            get {
                return ResourceManager.GetString("IdentityError_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain digits (0-9).
        /// </summary>
        public static string IdentityError_PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("IdentityError_PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain lower case letters (a - z).
        /// </summary>
        public static string IdentityError_PasswordRequiresLower {
            get {
                return ResourceManager.GetString("IdentityError_PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain non-alphanumeric char (. ! + ? ...).
        /// </summary>
        public static string IdentityError_PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("IdentityError_PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain &apos;{0}&apos; unique chracters.
        /// </summary>
        public static string IdentityError_PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("IdentityError_PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain lower case letters (A - Z).
        /// </summary>
        public static string IdentityError_PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("IdentityError_PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least &apos;{0}&apos; character long.
        /// </summary>
        public static string IdentityError_PasswordTooShort {
            get {
                return ResourceManager.GetString("IdentityError_PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is already in &apos;{0}&apos; role.
        /// </summary>
        public static string IdentityError_UserAlreadyInRole {
            get {
                return ResourceManager.GetString("IdentityError_UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in &apos;{0}&apos; role.
        /// </summary>
        public static string IdentityError_UserNotinRole {
            get {
                return ResourceManager.GetString("IdentityError_UserNotinRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string Success_General {
            get {
                return ResourceManager.GetString("Success_General", resourceCulture);
            }
        }
    }
}
