name: Publish 🚀

on: 
  workflow_dispatch:
  push:
    branches:
    - master

env:
  WEBAPP_NAME: base-project
  WEBAPP_PACKAGE_PATH: "./publish/"
  FTP_DISTANATION_URL: './wwwroot/'
  FTP_SERVER: 'site3637.siteasp.net'
  FTP_USERNAME: site3637
  FTP_PASSWORD: Ei7#8H@w+nM4
  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./Portfolio.sln

    - name: Build
      run: dotnet build ./Portfolio.sln --configuration Release --no-restore

    - name: Removing unnecessary files
      run: |
        echo "Removing files from server"
        curl -u "${{ env.FTP_USERNAME }}:${{ env.FTP_PASSWORD }}" ftp://${{ env.FTP_SERVER }} -Q "DELE /wwwroot/*"



    
