name: Publish 🚀

on: 
  workflow_dispatch:
  push:
    branches:
    - master

env:
  WEBAPP_NAME: base-project
  WEBAPP_PACKAGE_PATH: "./publish/"
  FTP_DISTANATION_URL: './wwwroot/'
  FTP_SERVER: 'site3637.siteasp.net'
  FTP_USERNAME: site3637
  FTP_PASSWORD: Ei7#8H@w+nM4
  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./Portfolio.sln

    - name: Build
      run: dotnet build ./Portfolio.sln --configuration Release --no-restore

    - name: Removing unnecessary files
      run: |
       rm -rf ${{ env.FTP_SERVER }}/wwwroot/

    - name: Publish
      run: dotnet publish ./Portfolio/Portfolio.csproj --configuration Release --no-build --output '${{ env.WEBAPP_PACKAGE_PATH }}'
    
    - name: Deployment
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ env.FTP_SERVER }}
        username: ${{ env.FTP_USERNAME }}
        password: ${{ env.FTP_PASSWORD }}
        local-dir: ${{ env.WEBAPP_PACKAGE_PATH }}
        server-dir: ${{env.FTP_DISTANATION_URL}}
