name: Publish 🚀

on: 
  workflow_dispatch:
  push:
    branches:
    - master

env:
  WEBAPP_NAME: base-project
  WEBAPP_PACKAGE_PATH: "./publish/"
  FTP_DISTANATION_URL: './wwwroot/'
  FTP_SERVER: 'site3637.siteasp.net'
  FTP_USERNAME: site3637
  FTP_PASSWORD: Ei7#8H@w+nM4
  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./Portfolio.sln

    - name: Build
      run: dotnet build ./Portfolio.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./Portfolio/Portfolio.csproj --configuration Release --no-build --output '${{ env.WEBAPP_PACKAGE_PATH }}'
  
    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Clean FTP Directory
      run: |
        lftp -e "set ftp:ssl-allow no; mirror --reverse --delete --verbose --dry-run ${env.WEBAPP_PACKAGE_PATH} ${env.FTP_DISTANATION_URL}; quit" -u ${env.FTP_USERNAME},${env.FTP_PASSWORD} ${env.FTP_SERVER}






    
