name: Publish 🚀

on: 
  workflow_dispatch:
  push:
    branches:
    - master

env:
  WEBAPP_NAME: base-project
  WEBAPP_PACKAGE_PATH: "./publish/"
  FTP_DISTANATION_URL: './wwwroot/'
  FTP_SERVER: 'site3637.siteasp.net'
  FTP_USERNAME: site3637
  FTP_PASSWORD: Ei7#8H@w+nM4
  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./Portfolio.sln

    - name: Build
      run: dotnet build ./Portfolio.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./Portfolio.sln --configuration Release --no-build --output '${{ env.WEBAPP_PACKAGE_PATH }}'

    - name: Stop website
      run: |
        # Requires elevated access on server (self-hosted runner)
        Invoke-Expression $(New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/Install-PowerShellRemoting.ps1') -ExecutionPolicy Bypass -NoProfile -InputFormat None
        Enter-PSSession -ComputerName <server_name> -Credential (New-Object System.Management.Automation.PSCredential -ArgumentList ${{ env.FTP_USERNAME }}, (ConvertTo-SecureString -Force -AsPlainText ${{ env.FTP_PASSWORD }}).ToArray()))
        Stop-Website -Name https://mini-portfolio.runasp.net/
        
    - name: Deployment
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ env.FTP_SERVER }}
        username: ${{ env.FTP_USERNAME }}
        password: ${{ env.FTP_PASSWORD }}
        local-dir: ${{ env.WEBAPP_PACKAGE_PATH }}
        server-dir: ${{env.FTP_DISTANATION_URL}}
        dangerous-clean-slate: true
